apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: 891376988072.dkr.ecr.eu-west-2.amazonaws.com/hello-world-flask:v1.0
        ports:
        - containerPort: 5000
